name: OpenSSL no-deprecated and LibreSSL

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest 

    strategy:
      matrix:
        ssl: [libressl, openssl]

    steps:
    - uses: actions/checkout@v2
    - name: make re/rem
      run: |
        git clone https://github.com/baresip/re.git
        git clone https://github.com/creytiv/rem.git
        for p in re rem; do cd $p && sudo PATH="$PATH" make install && cd - && sudo rm -Rf $p; done
        sudo ldconfig

    - name: make baresip
      run: make EXTRA_CFLAGS="-Iassets/${{ matrix.ssl }}/include -Werror" EXTRA_LFLAGS="-Lassets/${{ matrix.ssl }}" CCACHE=;
